### ISSUE TITLE
include_blank seems to broken since v3.3.0

### ISSUE THREAD

**Issue by kapso** [plataformatec/simple_form#1423] opened 2016-08-27 02:03 UTC
include_blank for input field is broken.

Works fine in `3.2.1` but after upgrade it stopped working.

**Comment by lucasmazza** [comment] 2016-08-27 14:32
@kapso can you provide a sample app or reproducible test case that we can look into and see what might have broken it?

**Comment by kapso** [comment] 2016-09-21 07:06
@lucasmazza #1427 is reporting the same exact issue

**Comment by VelizarHristov** [comment] 2016-11-26 10:43
On 3.3.1 I get an exception for the following code:

`f.input :address_id,
              collection: @addresses,
              label_method: :display,
              include_blank: false,
              required: true`

On 3.2.1, I used include_blank: false because otherwise I get a blank option on the top of the select which is selected by default, but my select box has only one option most of the time (few customers have multiple addresses), so the user usually doesn't need to do anything with the select. With a blank option, they will have to use the select always, most of the time to select the only option there.

On 3.3.1 everything works the same except that I get an error with include_blank: false. Without it, I get the unneeded blank field.

**Comment by sivagollapalli** [comment] 2016-12-08 07:16
This is not a simple form issue. It is related action view. https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/tags/base.rb#L125 raising this error.

**Comment by feliperenan** [comment] 2017-12-15 01:39
I'm closing this issue since we have another one with the same subject.

**Closed by feliperenan** 2017-12-15 01:39 UTC
