### ISSUE TITLE
Formating issue with bootstrap and date field

### ISSUE THREAD

**Issue by yoshie902a** [plataformatec/simple_form#1433] opened 2016-10-02 11:46 UTC
http://stackoverflow.com/questions/39816490/simpleform-dob-not-displaying-correctly

**Comment by yoshie902a** [comment] 2016-10-02 12:04
I think I found the needed correction:

**OLD**
config.wrappers :multi_select_date, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.optional :readonly
    b.use :label, class: 'control-label'
    b.wrapper tag: 'div', class: 'form-inline' do |ba|
      ba.use :input, class: 'form-control'
      ba.use :error, wrap_with: { tag: 'span', class: 'help-block' }
      ba.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
    end
end

**REVISED**
config.wrappers :multi_select_date, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
    b.use :html5
    b.optional :readonly
    b.use :label, class: 'col-sm-3 control-label'
    b.wrapper tag: 'div', class: 'col-sm-9' do |bb|
			bb.wrapper tag: 'div', class: 'form-inline' do |ba|
	      ba.use :input, class: 'form-control'
	      ba.use :error, wrap_with: { tag: 'span', class: 'help-block' }
	      ba.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
	    end””
		end
end





config.wrapper_mappings = {
    check_boxes: :vertical_radio_and_checkboxes,
    radio_buttons: :vertical_radio_and_checkboxes,
    file: :vertical_file_input,
    boolean: :vertical_boolean,
    datetime: :multi_select,
    date: :multi_select_date,
    time: :multi_select_date
}

**Comment by feliperenan** [comment] 2017-12-12 12:16
Hi @yoshie902a 

I'm not sure if it's an issue. As @rafaelfranca said, this is more related to the markup of your application and you can change it in the initializer if you want.

By now, I'm closing this issue. 

Thanks for the contribution 😄

**Closed by feliperenan** 2017-12-12 12:16 UTC

**Comment by diesl** [comment] 2019-08-01 09:53
Hi everybody, 

I am seeing the same issue and I think it is legitimate. Please consider to reopen the issue.

The problem is that the existing code (named "OLD" above) is perfect for Bootstrap's _vertical form layout_. But it is not working when using Bootstrap's _horizontal form layout_. Therefore the proposed code (named "NEW" above) should be added, instead of replacing the "old" one.

Note that the other types have distinct vertical and horizontal layouts, for example _vertical_radio_and_checkboxes_ and _horizontal_radio_and_checkboxes_, but this is missing for multi_select.

I have tested the proposed code and it is working for me.
