### ISSUE TITLE
undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by redrick** [plataformatec/simple_form#1447] opened 2016-12-06 13:11 UTC
My problem is that I have AR model, which has serialized attribute `data` and is serialized with a plain ruby object that includes `ActiveModel::Model` for validations.

what happens to me is that once object is submitted with validation error I am not able to load form again and I see:
```
undefined method `+' for nil:NilClass
```

which is pointing to particular line in code and I managed to get around it with small fix (will submit PR shortly)

the question here is if you can please help me find a solution here, or asses if what I did there is legit :)

Thank you :)

EDIT: 

forgot to mention that here is app to reproduce the problem: https://github.com/redrick/simple_form_error_demonstration

once you save user empty you will not be able to edit because of this mistake

**Comment by evertonts** [comment] 2017-01-20 16:44
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by redrick** [comment] 2017-01-21 23:04
Sorry if I did not make myself clear, I see this as an issue, I made my case with demonstration repo and opened PR with solution for it, is probably just my mistake by explaining it wrong, could you please have one more look?

**Comment by cavd** [comment] 2017-06-21 21:31
I have encountered this error, as well.  Since the PR has not been merged yet, is there a way to work around the issue outside of simple_form?

**Comment by gordysc** [comment] 2017-06-22 14:49
We also hit this last week... any help on this would be greatly appreciated

**Comment by feliperenan** [comment] 2017-12-07 16:11
Hi @redrick 

I tried to reproduce your issue but I couldn't.

![simple_form_issue](https://user-images.githubusercontent.com/27698968/33724823-9c57c75a-db57-11e7-82aa-52b981e7ddab.gif)

Did I forget something?

*PS:* I had to update the Rails to version 5.0.1. With the version listed in your Gemfile I got the [this error](https://github.com/rails/rails/issues/25185)

**Comment by redrick** [comment] 2017-12-07 22:16
Hi @feliperenan, sry I am out till monday, but will have a look then... we use my fork for now, but I know there was this problem, not quite sure gif captures it, but was some time ago... will refresh my memory when I get back and try to reproduce with gif like you did, so we are sure we are looking at the same thing :)

**Comment by redrick** [comment] 2017-12-15 11:46
Ok sorry for taking too long to respond...

I found out that what I pushed in that demonstration repo is already issue solved. SimpleForm is pointing to my repo where the fix is present, so I pointed it to up to date repo official repo and there I can still reproduce like you showed:

![simple_form](https://user-images.githubusercontent.com/865364/34040834-d28746fe-e195-11e7-9181-908879b5acfd.gif)

**Comment by feliperenan** [comment] 2017-12-15 12:21
@redrick no worries.

Tries to update your application to Rails 5.0.1. I tested your update here and it keeps working with me.

**Comment by redrick** [comment] 2017-12-15 13:33
OK I see, on rails 5 above works, would be worth looking into why...

Since this is just example is no problem upgrading, on the infrastructure we need to maintain is good amount of work to update to rails 5 and I am not completely sure when that will be...

So point taken, no excuses, simply update rails, but I don't want to close it since I hate that I have my fork in gemfile and will probably stay there for a while :(

Thanks for the tip here @feliperenan :)

**Comment by feliperenan** [comment] 2017-12-16 02:30
I think we can close this issue since it looks isn't a simple_form issue.

**Closed by feliperenan** 2017-12-16 02:30 UTC
