### ISSUE TITLE
Strange routing behavior when submitting forms with File upload/File field in Production

### ISSUE THREAD

**Issue by Rubioli** [plataformatec/simple_form#1641] opened 2019-02-14 15:43 UTC
In my application I'm using `carrierwave` for image upload.

My `CampaignsController` is a usual `create action`

    def create
      @campaign = Campaign.new(campaign_params)
    
      respond_to do |format|
        if @campaign.save
          format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
          format.json { render :show, status: :created, location: @campaign }
        else
          format.html { render :new }
          format.json { render json: @campaign.errors, status: :unprocessable_entity }
        end
      end
    end

Everything works fine in `development`, but in `production` after submit/save things go wrong.

By that I mean:
In `development` when form is submitted, after save it goes to `localhost:3000/campaigns/38` and my form is: `action="campaigns/38"`.

*BUT*

In **production** when form is submitted, after save, instead of going to `example.com/campaigns/38`, it goes to `example.com/campaigns/campaigns/38` and my form changes to: `action="campaigns/campaigns/38"`.

As you can see that extra `campaigns` is in the URL and I'm not sure why. It seems rails changed my root from `example.com` to `example.com/campaigns`

This is my `routes.rb`:

    Rails.application.routes.draw do
      resources :campaigns 
    
      # match '*any' => 'application#options', :via => [:options]
    end

This is my `ImageUploader`:

    class ImageUploader < CarrierWave::Uploader::Base
      include CarrierWave::MiniMagick
    
      storage :file
    
      def store_dir
          "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
      end
    
      version :large do
        resize_to_limit(600, 600)
      end

My `Campaign` Model:

    class Campaign < ApplicationRecord
      mount_uploader :image, ImageUploader

This is my application version:

    ruby "2.3.1"
    gem 'rails', '~> 5.2.2'

Everything works as long as `= f.input :image as: :file` is not there. when I remove `= f.input :image as: :file` from my `form` everything works fine in all ENVs, but when I add it back, its than `Production` has this strange behavior.

*PS: I've tested it without `carrierwave` because I thought maybe `carrierwave` is the issue but same problem*

Any help is appreciated and thanks in advance!

**Comment by feliperenan** [comment] 2019-02-14 15:56
Hi @Rubioli, thanks for the issue report.

Could you try the Rails default form to see if you are facing this issue only with Simple Form? If you are sure that it's a Simple Form issue, could you provide a sample application that reproduces this issue in isolation? that's would help us a lot to find the issue.

Thanks

**Comment by Rubioli** [comment] 2019-02-14 16:49
Thanks Felipe, @feliperenan for your reply and taking time for this

I just tested with `form_for` and still have the issue. I'm really sorry to report it here without testing `form_for`.

It's just been literally over 2 days trying to find whats the issue and you can imagine a bunch of gem updates & uninstalls :( and head to the wall haha

 I know maybe I go out of the line here but I'm kind of desperate :( since `Simple form` is still solid as a rock 🥇, have you ever encountered such an issue before and have some tips? *(again I know I might be out of line here and asking too much - but as they said, desperate time desperate measures. If not, I understand and I appreciate you taking time  💯 )*

**Comment by feliperenan** [comment] 2019-02-14 17:04
We could continue this conversation, but I gonna close the issue since it's not a Simple Form issue, right?

Is there any configuration in our production environment that may add this extra path to the route? You could check other routes of your application to see if they are ok. That's is my first guess 🤔

**Closed by feliperenan** 2019-02-14 17:04 UTC

**Comment by Rubioli** [comment] 2019-02-14 17:11
Thanks Flipe. You're the man 😃 Yeah I checked everything in my route and everything works fine and what basically makes me crazy is that the issue goes away when `File field` is not there *(I just tested it)*.

This is my whole *routes.rb*

```
Rails.application.routes.draw do
  root 'pages#dashboard'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :posts do
    collection do
      get :autocomplete
    end
    get 'changes', to: 'messages#deactivate_activate'
    put 'changes', to: 'messages#deactivate_activate'
  end

  resources :campaigns do
    get 'changes', to: 'campaigns#deactivate_activate'
    put 'changes', to: 'campaigns#deactivate_activate'
    get 'crop', to: 'campaigns#crop'
  end


  get 'quick/view/campaign', to: 'campaigns#quick_view', as: :campaign_quick_view

  get 'test', to: 'pages#test'

  # match '*any' => 'application#options', :via => [:options]

end
```

Felipe, you dont know how much I appreciate you taking your time 🔸

**Comment by feliperenan** [comment] 2019-02-14 17:25
I don't see nothing wrong in your routes. Are you able to reproduce this issue in sample-app that I can access to see what is happening?

**Comment by Rubioli** [comment] 2019-02-14 17:33
Sure Felipe, I'll create it. But since the issue only accrues in production, would I need to set up a server? *(because in development it works perfectly)*

Just to see all the corners, I'm using `carrierwave` for upload and `carrierwave-aws` *(But I believe the problem was there before I even added `carrierwave-aws`)*. Do you think that could be something?

on the other hand, I've other applications on productions that running `carrierwave` with no issue. I've never seen this thing 😞 


Btw one unrelated thing. I'll be moving to São Paulo within this year and I owe you a drink for your help 💯

**Comment by feliperenan** [comment] 2019-02-14 17:36
You could make a small application and deploy on Heroku than we could debug to see what is happening. 

> Btw one unrelated thing. I'll be moving to São Paulo within this year and I owe you a drink for your help 💯
I'll be waiting for it 🍺 🍺

**Comment by Rubioli** [comment] 2019-02-14 17:38
You're the man 👍 I'll be setting up now and deploy to heroku. I'll be sending you the link. Thanks a lot 💯 

> I'll be waiting for it 🍺 🍺
> You'll get it 🍺

**Comment by Rubioli** [comment] 2019-02-15 15:26
Hi again @feliperenan.

I'm setting up the sample application *(its a big project)* so a lot of things that needs to be removed haha.

In the meanwhile, I would appreciate if you could let me know if this makes sense 😄 

as you know one of the `gems` that would be in *uploading* process, is `carrierwave-aws` so I asked if their gem would be the issue and they said:

> This seems like a host/asset_host configuration problem in production
> Also, from your routes it looks like you are using ActiveStorage as well, which you would use _instead_ of CarrierWave. If you're starting a new application and want to do it The Rails Way, you may want to use ActiveStorage instead.

Would this makes sense and could you please give me some pointers regarding this 💯 

again, thanks a lot for taking you time 😃

**Comment by feliperenan** [comment] 2019-02-18 20:17
HI @Rubioli, sorry about the delay response. 

I didn't use Active Storage yet so and I'm not familiar with carrierwave gem. I found out this blog post that may help you to setup it:

http://phase2online.com/blog/2018/10/03/easily-upload-files-with-active-storage-in-rails-5-2/

Also, I think that it worth a look at the official documentation:

https://edgeguides.rubyonrails.org/active_storage_overview.html

Hope it helps 🤞
