### ISSUE TITLE
Missing Rails Generator

### ISSUE THREAD

**Issue by Silvery-Corgan** [plataformatec/simple_form#1321] opened 2015-11-12 17:57 UTC
Getting the following error:
```
$ rails generate simple_form:install --boostrap
Could not find generator 'simple_form:install'. Maybe you meant 'integration_test', 'scaffold' or 'active_record:model'
Run 'rails generate --help' for more options.
```

Using the latest version 3.2.0 with rails 4.2.4 installed with RVM.
```
$ rails --version
Rails 4.2.4
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
$ rvm -v
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```
Bundle Install executes successfully:
```
$ bundle install
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.2
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.4
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using loofah 2.0.3
Using rails-html-sanitizer 1.0.2
Using actionview 4.2.4
Using rack 1.6.4
Using rack-test 0.6.3
Using actionpack 4.2.4
Using globalid 0.3.6
Using activejob 4.2.4
Using mime-types 2.6.2
Using mail 2.6.3
Using actionmailer 4.2.4
Using activemodel 4.2.4
Using arel 6.0.3
Using activerecord 4.2.4
Using execjs 2.6.0
Using autoprefixer-rails 6.1.0.1
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.2
Using sass 3.4.19
Using bootstrap-sass 3.3.5.1
Using bundler 1.10.6
Using byebug 8.2.0
Using coffee-script-source 1.10.0
Using coffee-script 2.4.1
Using thor 0.19.1
Using railties 4.2.4
Using coffee-rails 4.1.0
Using font-awesome-sass 4.4.0
Using multi_json 1.11.2
Using jbuilder 2.3.2
Using jquery-rails 4.0.5
Using pg 0.18.3
Using sprockets 3.4.0
Using sprockets-rails 2.3.3
Using rails 4.2.4
Using rdoc 4.2.0
Using tilt 2.0.1
Using sass-rails 5.0.4
Using sdoc 0.4.1
Using simple_form 3.2.0
Using spring 1.4.1
Using turbolinks 2.5.3
Using uglifier 2.7.2
Using web-console 2.2.1
Bundle complete! 16 Gemfile dependencies, 57 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```
My Gemfile has it included:

`gem 'simple_form'`

Using it with 'migration' doesn't work as it throws eception:
```
$ rails generate migration simple_form:install --boostrap
      invoke  active_record
~/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/rails/generators/active_record/migration/migration_generator.rb:61:in `validate_file_name!':  (ActiveRecord::IllegalMigrationNameError)

Illegal name for migration file: simple_form:install
	(only lower case letters, numbers, and '_' allowed)

	from ~/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/rails/generators/active_record/migration/migration_generator.rb:10:in `create_migration_file'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/group.rb:277:in `block in _invoke_for_class_method'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/shell.rb:68:in `with_padding'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/group.rb:266:in `_invoke_for_class_method'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/group.rb:133:in `_invoke_from_option_orm'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from ~/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/generators.rb:157:in `invoke'
	from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
	from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from ~/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ~/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by nashby** [comment] 2015-11-12 18:22
@Silvery-Corgan `rails generate migration simple_form:install --boostrap` is not a correct way of calling install generator. The first one you posted (`rails generate simple_form:install --boostrap`) is correct one. Can you please try to run it with `bundle exec rails generate simple_form:install --boostrap`?

**Comment by Silvery-Corgan** [comment] 2015-11-12 18:24
```
$ bundle exec rails generate simple_form:install --boostrap
Could not find generator 'simple_form:install'. Maybe you meant 'integration_test', 'scaffold' or 'active_record:model'
Run `rails generate --help` for more options.
```

**Comment by nashby** [comment] 2015-11-12 18:29
@Silvery-Corgan looks like something is wrong with your app.  Can you please provide a sample application that reproduces the error?

**Comment by nashby** [comment] 2015-11-12 18:31
Closing it since it's not simple_form's issue.

**Closed by nashby** 2015-11-12 18:31 UTC

**Comment by rafaelfranca** [comment] 2015-11-12 18:40
If you are using spring, try to restart it

**Comment by klapperkopp** [comment] 2017-12-27 15:33
I am having the same issue with rails 5.1.4, ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux].
I does not find the generator and spring restart doesn't fix it.
The generators of any other gem like devise/blazer/erd/responders do work without any problem.

**Comment by feliperenan** [comment] 2017-12-27 20:46
@klapperkopp I tested it right now and it is working normally. Could you provide a sample application that reproduces the error?

**Comment by klapperkopp** [comment] 2018-12-03 12:34
Hi, I just saw this now. Sorry I couldn't provide that. I don't use simple_forms anymore since that problem.

**Comment by pedroVflight** [comment] 2019-11-18 19:40
> ```
> $ bundle exec rails generate simple_form:install --boostrap
> Could not find generator 'simple_form:install'. Maybe you meant 'integration_test', 'scaffold' or 'active_record:model'
> Run `rails generate --help` for more options.
> ```

Try to stop sprin `spring stop`
Then run the rails command
And then start spring again `spring start`

**Comment by fatifleu** [comment] 2020-05-25 16:52
i also have the same issue.
Could not find generator 'simple_form:install'.
Run `rails generate --help` for more options.
i am ussing rails version 6.0.3.1

**Comment by Rumbie-Mudzie7** [comment] 2020-09-14 11:51
@pedroVflight 
Thank you the solution, it worked wonders for me, after trying a lot of solutions that didn't work.

**Comment by Russell108** [comment] 2025-08-02 09:59
I had the same issue Could not find generator 'simple_form:install'. 

I had to install spring gem in rails 8
